/*
 * Production and Distribution Tracking API
 *
 * API for monitoring the production and distribution of documents or currency in real-time, ensuring transparency and security in the distribution chain.
 *
 * API version: 1.0.0
 * Contact: support@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DistributionsBody struct {

	BatchId int32 `json:"batch_id"`

	SerialNumber string `json:"serial_number"`

	Location string `json:"location"`
}
