/*
 * Production and Distribution Tracking API
 *
 * API for monitoring the production and distribution of documents or currency in real-time, ensuring transparency and security in the distribution chain.
 *
 * API version: 1.0.0
 * Contact: support@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {

	Id int32 `json:"id,omitempty"`

	BatchId int32 `json:"batch_id,omitempty"`

	SerialNumber string `json:"serial_number,omitempty"`

	Location string `json:"location,omitempty"`
}
