/*
 * Production and Distribution Tracking API
 *
 * API for monitoring the production and distribution of documents or currency in real-time, ensuring transparency and security in the distribution chain.
 *
 * API version: 1.0.0
 * Contact: support@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	Id int32 `json:"id,omitempty"`

	BatchNumber string `json:"batch_number,omitempty"`

	TotalUnits int32 `json:"total_units,omitempty"`

	Status string `json:"status,omitempty"`
}
