/*
 * Production and Distribution Tracking API
 *
 * API for monitoring the production and distribution of documents or currency in real-time, ensuring transparency and security in the distribution chain.
 *
 * API version: 1.0.0
 * Contact: support@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/",
		Index,
	},

	Route{
		"RegisterUser",
		strings.ToUpper("Post"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/auth/register",
		RegisterUser,
	},

	Route{
		"UserLogin",
		strings.ToUpper("Post"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/auth/login",
		UserLogin,
	},

	Route{
		"CreateDistribution",
		strings.ToUpper("Post"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/distributions",
		CreateDistribution,
	},

	Route{
		"GetDistributions",
		strings.ToUpper("Get"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/distributions",
		GetDistributions,
	},

	Route{
		"CreateProductionBatch",
		strings.ToUpper("Post"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/production-batches",
		CreateProductionBatch,
	},

	Route{
		"DeleteProductionBatch",
		strings.ToUpper("Delete"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/production-batches/{batch_id}",
		DeleteProductionBatch,
	},

	Route{
		"GetProductionBatches",
		strings.ToUpper("Get"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/production-batches",
		GetProductionBatches,
	},

	Route{
		"UpdateProductionBatch",
		strings.ToUpper("Put"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/production-batches/{batch_id}",
		UpdateProductionBatch,
	},

	Route{
		"GetDistributionReport",
		strings.ToUpper("Get"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/reports/distribution",
		GetDistributionReport,
	},

	Route{
		"GetProductionReport",
		strings.ToUpper("Get"),
		"/MUHAMADHAZELRAFIANTO/API_Sistem_Pelacakan_Produksi_dan_Distribusi/1.0.0/reports/production",
		GetProductionReport,
	},
}
